name: CI config

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Win build
        options: 
        - build
        - build+test
        - build+test+publish
      message:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: DO smth
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('github') }} ${{ github.event.inputs.name }}"