name: CI config

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Win build
        options: 
        - build
        - build+test
        - build+test+publish
      message:
        required: true

env:
  WIN_CHOICE: ${{ github.event.inputs.name }}
  MESSAGE: ${{ github.event.inputs.message }}

jobs:
  print_info:
    runs-on: ubuntu-latest

    steps:
    - name: Print inputs & github context
      run: |
        echo '${{ toJSON(github) }}'
        echo '${{ toJSON(env) }}'
    - name: checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - id: save-value
      uses: marcoslopes/git-notes-action@v1
      with:
        sha: ${{ github.sha }}
        message: "${{ env.WIN_CHOICE }}"