name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Win build
        options: 
        - not today...
        - build & test
        - build & test & publish artifact
      message:
        required: true
      name:
        type: boolean
        description: Nix build
      message:
        required: true

jobs:
  set_options_vars:
    runs-on: ubuntu-latest

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"