name: Create release

on:
  push:
    branches:
      - 'ci_config'
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Print tag
        run: echo ${{ steps.get_version.outputs.VERSION }}