name: Create release

on:
  push:
    branches:
      - 'ci_config'
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag env
        run: |
          git log -n 5 | grep -iE 'tag: v.*.*.*'