name: Win Build

on:
  workflow_run:
    workflows: [Rusty-build]
    types: completed

jobs:
  print_info:
    runs-on: ubuntu-latest

    steps:
    - name: Print inputs & github context
      run: |
        # echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
        # echo "win_choice=${{ github.event.inputs.name }}" >> $GITHUB_ENV
        # echo '${{ toJSON(github) }}'
        # echo '${{ toJSON(env) }}'
    - id: get-value
      uses: marcoslopes/git-notes-action@v1
      with:
          sha: ${{ github.sha }}
  
    - id: use-value
      run: |
          echo "value from note ${{ steps.get-value.outputs.message }}"
