name: Win Build

on:
  workflow_run:
    workflows: [CI config]
    types: completed

jobs:
  print_info:
    runs-on: ubuntu-latest

    steps:
    - name: Print inputs & github context
      run: |
        # echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
        # echo "win_choice=${{ github.event.inputs.name }}" >> $GITHUB_ENV
        echo '${{ toJSON(github) }}'
        echo '${{ toJSON(env) }}'    