name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_request_removed
      - review_requested
      - synchronize
      - unlabeled
      - edited
      - opened
  pull_request_review:
    types:
      - dismissed
      - submitted

jobs:
  prcheck:
    runs-on: ubuntu-latest
    # if: contains(github.event.pull_request.body, 'ready_to_merge')
    steps:
      - name: flag reaction
        run: echo "hello!"
