name: Merge Bot

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - review_requested
      - synchronize
      - edited
      - opened
  pull_request_comment:
    types:
      - edited
      - submitted

jobs:
  prcheck:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.body, 'ready_to_merge')
    steps:
      - name: flag reaction
        run: echo "${{ github.event.pull_request.body }}"
      - name: Integration check
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: false
          reviewers: false
          labels: ready to merge
          blocking_labels: do not merge
          checks_enabled: true
          method: merge
          delete_source_branch: true
