name: Merge Bot

on:
  pull_request:
    types:
      - labeled

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  local_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Merge master to PR source locally
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "$DEFAULT_BRANCH"
          git status
          git checkout "$GITHUB_HEAD_REF"
          git merge "$DEFAULT_BRANCH" --no-edit
          git status
      - name: Run tests
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo test --release
  merge_bot:
    needs: local_merge
    steps:
      - name: Merge bot
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          test: true
          reviewers: true
          labels: ready to merge
          blocking_labels: do not merge
          checks_enabled: false
          method: merge
          delete_source_branch: true
      - name: Remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: ready to merge