name: Rusty-build

on:
  push:
    branches:
      - main
      - rust-flow
  pull_request:

env:
  CARGO_TERM_COLOR: always
  APP_DIR: ${{ github.workspace }}/target/release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: build release version
    runs-on: ${{ matrix.os }}
    steps:
      - name: Linux
        if: ${{ env.matrix.os == 'ubuntu-latest' }}
        uses: actions/checkout@v2
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: MacOS
        run: |
          pwd
          ls -hal
          echo "Hi! I'm Linux agent!"
          cargo build
      - name: Windows
        if: ${{ env.matrix.os == 'Windows' }}
        run: |
          echo "Hi! I'm Windows agent!"

      - name: MacOS
        if: ${{ env.matrix.os == 'macos-latest' }}
        uses: actions/checkout@v2
        run: |
          echo "Hi! I'm Mac :)"