name: Rusty-build

on:
  push:
    branches:
      - main
      - rust-flow
  pull_request:

env:
  CARGO_TERM_COLOR: always
  APP_DIR: ${{ github.workspace }}/target/release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: build release version
    runs-on: ${{ matrix.os }}
    steps:
      - name: Linux
        if: ${{ runner.os == 'Ubuntu' }}
        run: echo "Hi! I'm Linux agent!"
      - name: Windows
        if: ${{ runner.os == 'Windows' }}
        run: echo "Hi! I'm Windows agent!"
      - name: MacOS
        if: ${{ runner.os == 'macOS' }}
        run: echo "Hi! I'm Mac i i suck! :)"