name: Rusty-build

on:
  push:
    branches:
      - main
      - rust-flow
  pull_request:

env:
  CARGO_TERM_COLOR: always
  APP_DIR: ${{ github.workspace }}/target/release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
    name: build release version
    runs-on: ${{ matrix.os }}
    if: 
    steps:
      - name: Linux
        if: [ "$RUNNER_OS" == "Linux" ]
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          echo "Hi! I'm Linux agent!"
          cargo build --release
      - name: Windows
        if: [ "$RUNNER_OS" == "Windows" ]
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          echo "Hi! I'm Windows agent!"
          cargo build --release
      - name: MacOS
        if: [ "$RUNNER_OS" == "macOS" ]
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          echo "Hi! I'm Mac i i suck! :)"
          cargo build --release